In [1]:
import torch
M=torch.rand(1,3)
N=torch.rand(2,1)
print(M-N)

print(torch.sub(M,N))

M.sub_(N)
print(M)

tensor([[-0.6604, -0.7471, -0.1990],
        [ 0.0926,  0.0060,  0.5541]])
tensor([[-0.6604, -0.7471, -0.1990],
        [ 0.0926,  0.0060,  0.5541]])


RuntimeError: output with shape [1, 3] doesn't match the broadcast shape [2, 3]

In [2]:
import torch
P=torch.normal(0,0.01,(3,2))
print(P)
Q=torch.normal(0,0.01,(4,2))
print(Q)
Q.t_()
print(Q)
print(torch.mm(P,Q))

tensor([[-0.0031, -0.0002],
        [-0.0050,  0.0135],
        [ 0.0105,  0.0010]])
tensor([[-0.0013,  0.0051],
        [-0.0008, -0.0007],
        [ 0.0030,  0.0135],
        [ 0.0099,  0.0192]])
tensor([[-0.0013, -0.0008,  0.0030,  0.0099],
        [ 0.0051, -0.0007,  0.0135,  0.0192]])
tensor([[ 2.8789e-06,  2.6929e-06, -1.2767e-05, -3.5397e-05],
        [ 7.6108e-05, -5.3099e-06,  1.6724e-04,  2.1020e-04],
        [-9.2001e-06, -9.2431e-06,  4.5005e-05,  1.2267e-04]])


In [3]:
import torch
x=torch.tensor(1.,requires_grad=True)
y1=x*x
with torch.no_grad():
    y2=x*x*x
y3=y1+y2
out=y3.mean()
out.backward()
print(x.grad)

tensor(2.)
